import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hora do português</h1>
        <h2 className={styles.subtitle}>Portuguese Time</h2>

        <p className={styles.description}>Get started doing some flashcards </p>

        <div className={styles.card}>
          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <p
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Feito com amor por{' '}
          <span>
            <a
              className={styles.link}
              href="https://github.com/viniavena"
              target="_blank"
              rel="noopener noreferrer"
            >
              Vini Avena
            </a>
          </span>
        </p>
      </footer>
    </div>
  );
}
