import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Flashcard from '../components/flashcard';

const flashcard = {
  word: 'Casa',
  translation: 'House',
  example: 'Eu moro em uma casa bonita.',
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hora do português</h1>
        <h2 className={styles.subtitle}>Portuguese Time</h2>

        <Flashcard {...flashcard} />
      </main>

      <footer className={styles.footer}>
        <p
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Feito com amor por{' '}
          <span>
            <a
              className={styles.link}
              href="https://github.com/viniavena"
              target="_blank"
              rel="noopener noreferrer"
            >
              Vini Avena
            </a>
          </span>
        </p>
      </footer>
    </div>
  );
}
